// SQLite schema v2. JSON columns hold field-presence/extension metadata, not core values.
export const VERSION = 2;
export const SCHEMA = `
CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL, description TEXT NOT NULL);
CREATE TABLE recordings(id TEXT PRIMARY KEY, reference_only INTEGER NOT NULL DEFAULT 1 CHECK(reference_only=1));
CREATE TABLE configurations(id TEXT PRIMARY KEY, config_scope TEXT NOT NULL DEFAULT 'processing', processor TEXT, prompt TEXT, notes_prompt TEXT, splitter TEXT, grouping_model TEXT, notes_model TEXT, reasoning TEXT, embedding_model TEXT, embedding_dimensions INTEGER CHECK(embedding_dimensions>0), embedding_version TEXT, normalization TEXT, metadata_json TEXT NOT NULL);
CREATE TABLE meetings(id TEXT PRIMARY KEY, user_id TEXT NOT NULL, fingerprint TEXT, source_key TEXT, title TEXT, meeting_date TEXT, status TEXT CHECK(status IN ('draft','processing','ready','failed')), stage TEXT, error TEXT, attempts INTEGER CHECK(attempts>=0), created_at TEXT, updated_at TEXT, revision_id TEXT, desired_revision_id TEXT, published_generation_id TEXT, job_id TEXT, pipeline_schema INTEGER, original_revision_id TEXT NOT NULL, evidence_id TEXT, artifact_id TEXT, config_id TEXT REFERENCES configurations(id), metadata_json TEXT NOT NULL,
 UNIQUE(user_id,fingerprint), UNIQUE(user_id,source_key),
 FOREIGN KEY(revision_id) REFERENCES memory_revisions(id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(desired_revision_id) REFERENCES memory_revisions(id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(original_revision_id) REFERENCES memory_revisions(id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(published_generation_id) REFERENCES memory_generations(id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(job_id) REFERENCES memory_jobs(id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(evidence_id) REFERENCES evidence_sets(id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(artifact_id) REFERENCES artifacts(id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE meeting_participants(meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE, ordinal INTEGER NOT NULL, name TEXT NOT NULL, PRIMARY KEY(meeting_id,ordinal));
CREATE TABLE evidence_sets(id TEXT PRIMARY KEY, meeting_id TEXT REFERENCES meetings(id) ON DELETE CASCADE, metadata_json TEXT NOT NULL);
CREATE TABLE speakers(evidence_id TEXT NOT NULL REFERENCES evidence_sets(id) ON DELETE CASCADE, id TEXT NOT NULL, ordinal INTEGER NOT NULL, label TEXT NOT NULL, provider_label TEXT, confirmed_name TEXT, confirmed_at TEXT, metadata_json TEXT NOT NULL, PRIMARY KEY(evidence_id,id), UNIQUE(evidence_id,ordinal));
CREATE TABLE transcript_segments(evidence_id TEXT NOT NULL REFERENCES evidence_sets(id) ON DELETE CASCADE, id TEXT NOT NULL, ordinal INTEGER NOT NULL, start_offset INTEGER NOT NULL CHECK(start_offset>=0), end_offset INTEGER NOT NULL CHECK(end_offset>start_offset), speaker_id TEXT, attribution TEXT, attribution_status TEXT, segment_text TEXT, provider_segment_id TEXT, provider_speaker TEXT, provider_overlap INTEGER CHECK(provider_overlap IN (0,1)), audio_recording_id TEXT REFERENCES recordings(id), audio_start_ms REAL CHECK(audio_start_ms>=0), audio_end_ms REAL, timing_source TEXT, metadata_json TEXT NOT NULL,
 PRIMARY KEY(evidence_id,id), UNIQUE(evidence_id,ordinal), FOREIGN KEY(evidence_id,speaker_id) REFERENCES speakers(evidence_id,id) DEFERRABLE INITIALLY DEFERRED, CHECK(audio_end_ms IS NULL OR audio_end_ms>audio_start_ms));
CREATE TABLE transcript_provenance(evidence_id TEXT PRIMARY KEY REFERENCES evidence_sets(id) ON DELETE CASCADE, kind TEXT, recording_id TEXT REFERENCES recordings(id), trace_id TEXT, model TEXT, status TEXT, diarization_id TEXT, names_key TEXT, metadata_json TEXT NOT NULL);
CREATE TABLE memory_revisions(id TEXT PRIMARY KEY, meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, title TEXT, meeting_date TEXT, original_text TEXT NOT NULL, content_hash TEXT, created_at TEXT, evidence_id TEXT NOT NULL REFERENCES evidence_sets(id) DEFERRABLE INITIALLY DEFERRED, internal_snapshot INTEGER NOT NULL DEFAULT 0, metadata_json TEXT NOT NULL);
CREATE TABLE revision_participants(revision_id TEXT NOT NULL REFERENCES memory_revisions(id) ON DELETE CASCADE, ordinal INTEGER NOT NULL, name TEXT NOT NULL, PRIMARY KEY(revision_id,ordinal));
CREATE TABLE source_units(unit_key TEXT PRIMARY KEY, revision_id TEXT NOT NULL REFERENCES memory_revisions(id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK(kind IN ('unit','legacy')), id TEXT NOT NULL, ordinal INTEGER NOT NULL, start_offset INTEGER NOT NULL CHECK(start_offset>=0), end_offset INTEGER NOT NULL CHECK(end_offset>start_offset), original_text TEXT NOT NULL, metadata_json TEXT NOT NULL, UNIQUE(revision_id,kind,id), UNIQUE(revision_id,kind,ordinal));
CREATE TABLE artifacts(id TEXT PRIMARY KEY, meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, revision_id TEXT NOT NULL REFERENCES memory_revisions(id), organization_model TEXT, embedding_model TEXT, answer_model TEXT, metadata_json TEXT NOT NULL);
CREATE TABLE artifact_passages(artifact_id TEXT NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE, ordinal INTEGER NOT NULL, unit_key TEXT NOT NULL REFERENCES source_units(unit_key), PRIMARY KEY(artifact_id,ordinal));
CREATE TABLE topics(artifact_id TEXT NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK(kind IN ('source','derived')), id TEXT NOT NULL, ordinal INTEGER NOT NULL, title TEXT NOT NULL, summary_text TEXT, derived INTEGER, metadata_json TEXT NOT NULL, PRIMARY KEY(artifact_id,kind,id), UNIQUE(artifact_id,kind,ordinal));
CREATE TABLE topic_sources(artifact_id TEXT NOT NULL, topic_kind TEXT NOT NULL, topic_id TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('members','summary')), ordinal INTEGER NOT NULL, unit_key TEXT NOT NULL REFERENCES source_units(unit_key), PRIMARY KEY(artifact_id,topic_kind,topic_id,role,ordinal), FOREIGN KEY(artifact_id,topic_kind,topic_id) REFERENCES topics(artifact_id,kind,id) ON DELETE CASCADE);
CREATE TABLE topic_items(artifact_id TEXT NOT NULL, topic_id TEXT NOT NULL, topic_kind TEXT NOT NULL DEFAULT 'derived' CHECK(topic_kind='derived'), ordinal INTEGER NOT NULL, kind TEXT NOT NULL, item_text TEXT NOT NULL, owner TEXT, deadline TEXT, metadata_json TEXT NOT NULL, PRIMARY KEY(artifact_id,topic_id,ordinal), FOREIGN KEY(artifact_id,topic_kind,topic_id) REFERENCES topics(artifact_id,kind,id) ON DELETE CASCADE);
CREATE TABLE item_sources(artifact_id TEXT NOT NULL, topic_id TEXT NOT NULL, item_ordinal INTEGER NOT NULL, ordinal INTEGER NOT NULL, unit_key TEXT NOT NULL REFERENCES source_units(unit_key), PRIMARY KEY(artifact_id,topic_id,item_ordinal,ordinal), FOREIGN KEY(artifact_id,topic_id,item_ordinal) REFERENCES topic_items(artifact_id,topic_id,ordinal) ON DELETE CASCADE);
CREATE TABLE cleaned_passages(artifact_id TEXT NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE, ordinal INTEGER NOT NULL, unit_key TEXT NOT NULL REFERENCES source_units(unit_key), cleaned_text TEXT NOT NULL, small_talk INTEGER CHECK(small_talk IN (0,1)), metadata_json TEXT NOT NULL, PRIMARY KEY(artifact_id,ordinal));
CREATE TABLE omissions(artifact_id TEXT NOT NULL REFERENCES artifacts(id) ON DELETE CASCADE, ordinal INTEGER NOT NULL, unit_key TEXT NOT NULL REFERENCES source_units(unit_key), reason TEXT NOT NULL, metadata_json TEXT NOT NULL, PRIMARY KEY(artifact_id,ordinal), UNIQUE(artifact_id,unit_key));
CREATE TABLE memory_generations(id TEXT PRIMARY KEY, meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE, revision_id TEXT NOT NULL REFERENCES memory_revisions(id), status TEXT NOT NULL CHECK(status IN ('building','published')), legacy INTEGER, created_at TEXT, config_id TEXT REFERENCES configurations(id), artifact_id TEXT REFERENCES artifacts(id), internal_building INTEGER NOT NULL DEFAULT 0, metadata_json TEXT NOT NULL);
CREATE TABLE memory_source_chunks(id TEXT PRIMARY KEY, meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE, generation_id TEXT REFERENCES memory_generations(id) ON DELETE CASCADE, revision_id TEXT NOT NULL REFERENCES memory_revisions(id), topic_id TEXT, topic_artifact_id TEXT, topic_kind TEXT DEFAULT 'source', part INTEGER, title TEXT, body TEXT NOT NULL, input_hash TEXT, primary_unit_key TEXT REFERENCES source_units(unit_key), config_id TEXT REFERENCES configurations(id), metadata_json TEXT NOT NULL, FOREIGN KEY(topic_artifact_id,topic_kind,topic_id) REFERENCES topics(artifact_id,kind,id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE chunk_sources(chunk_id TEXT NOT NULL REFERENCES memory_source_chunks(id) ON DELETE CASCADE, role TEXT NOT NULL CHECK(role IN ('members','context','link')), ordinal INTEGER NOT NULL, unit_key TEXT NOT NULL REFERENCES source_units(unit_key), start_offset INTEGER, end_offset INTEGER, evidence_id TEXT REFERENCES evidence_sets(id), metadata_json TEXT, PRIMARY KEY(chunk_id,role,ordinal));
CREATE TABLE embeddings(chunk_id TEXT PRIMARY KEY REFERENCES memory_source_chunks(id) ON DELETE CASCADE, model TEXT, dimensions INTEGER NOT NULL CHECK(dimensions>0), config_version TEXT, normalization TEXT, input_hash TEXT, vector BLOB NOT NULL, CHECK(length(vector)=dimensions*8));
CREATE TABLE legacy_chunk_aliases(meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE, passage_id TEXT NOT NULL, chunk_id TEXT NOT NULL REFERENCES memory_source_chunks(id) ON DELETE CASCADE, fields_json TEXT NOT NULL, PRIMARY KEY(meeting_id,passage_id));
CREATE VIEW chunks AS SELECT a.meeting_id,a.passage_id,c.id,c.body FROM legacy_chunk_aliases a JOIN memory_source_chunks c ON c.id=a.chunk_id;
CREATE TABLE memory_jobs(id TEXT PRIMARY KEY, meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE, revision_id TEXT NOT NULL REFERENCES memory_revisions(id), generation_id TEXT NOT NULL REFERENCES memory_generations(id) DEFERRABLE INITIALLY DEFERRED, run_id TEXT, lease_until INTEGER, status TEXT NOT NULL, stage TEXT, attempts INTEGER CHECK(attempts>=0), error TEXT, updated_at TEXT, window_index INTEGER CHECK(window_index>=0), checkpoint_artifact_id TEXT REFERENCES artifacts(id), config_id TEXT REFERENCES configurations(id), metadata_json TEXT NOT NULL);
CREATE TABLE diarizations(id TEXT PRIMARY KEY, user_id TEXT NOT NULL, recording_id TEXT REFERENCES recordings(id), status TEXT NOT NULL, error TEXT, attempts INTEGER CHECK(attempts>=0), created_at TEXT, metadata_json TEXT NOT NULL);
CREATE TABLE diarized_transcripts(id TEXT PRIMARY KEY REFERENCES diarizations(id) ON DELETE CASCADE, recording_id TEXT REFERENCES recordings(id), provider TEXT, model TEXT, provider_request_id TEXT, audio_sha256 TEXT, audio_byte_size INTEGER CHECK(audio_byte_size>0), duration_ms REAL CHECK(duration_ms>0), saved_audio_duration_ms REAL CHECK(saved_audio_duration_ms>0), original_text TEXT NOT NULL, provider_text TEXT, created_at TEXT, evidence_id TEXT NOT NULL REFERENCES evidence_sets(id), metadata_json TEXT NOT NULL);
CREATE TABLE diarized_selections(source_id TEXT PRIMARY KEY, meeting_id TEXT NOT NULL REFERENCES meetings(id) ON DELETE CASCADE);
CREATE TABLE answers(id TEXT PRIMARY KEY, user_id TEXT NOT NULL, question TEXT, status TEXT, scope TEXT, requested_speaker TEXT, clarification TEXT, limitation TEXT, ready_meeting_count INTEGER, retrieval_truncated INTEGER, model TEXT, created_at TEXT, filter_participant TEXT, filter_date_from TEXT, filter_date_to TEXT, metadata_json TEXT NOT NULL);
CREATE TABLE answer_meeting_filters(answer_id TEXT NOT NULL REFERENCES answers(id) ON DELETE CASCADE, ordinal INTEGER NOT NULL, requested_meeting_id TEXT NOT NULL, PRIMARY KEY(answer_id,ordinal));
CREATE TABLE answer_sources(answer_id TEXT NOT NULL REFERENCES answers(id) ON DELETE CASCADE, ordinal INTEGER NOT NULL, meeting_id TEXT REFERENCES meetings(id), referenced_meeting_id TEXT, referenced_revision_id TEXT, referenced_generation_id TEXT, passage_id TEXT, resolved_unit_key TEXT REFERENCES source_units(unit_key), resolved_generation_id TEXT REFERENCES memory_generations(id), resolution TEXT NOT NULL CHECK(resolution IN ('exact','snapshot_only')), meeting_title TEXT, meeting_date TEXT, start_offset INTEGER, end_offset INTEGER, original_text TEXT NOT NULL, starts_at_line_boundary INTEGER, evidence_id TEXT REFERENCES evidence_sets(id), metadata_json TEXT NOT NULL, PRIMARY KEY(answer_id,ordinal));
CREATE TABLE answer_source_participants(answer_id TEXT NOT NULL, source_ordinal INTEGER NOT NULL, ordinal INTEGER NOT NULL, name TEXT NOT NULL, PRIMARY KEY(answer_id,source_ordinal,ordinal), FOREIGN KEY(answer_id,source_ordinal) REFERENCES answer_sources(answer_id,ordinal) ON DELETE CASCADE);
CREATE TABLE answer_statements(answer_id TEXT NOT NULL REFERENCES answers(id) ON DELETE CASCADE, ordinal INTEGER NOT NULL, statement_text TEXT NOT NULL, kind TEXT NOT NULL, metadata_json TEXT NOT NULL, PRIMARY KEY(answer_id,ordinal));
CREATE TABLE answer_citations(answer_id TEXT NOT NULL, statement_ordinal INTEGER NOT NULL, ordinal INTEGER NOT NULL, source_ordinal INTEGER NOT NULL, referenced_meeting_id TEXT, referenced_revision_id TEXT, referenced_generation_id TEXT, passage_id TEXT, quote TEXT NOT NULL, speaker TEXT, segment_id TEXT, metadata_json TEXT NOT NULL, PRIMARY KEY(answer_id,statement_ordinal,ordinal), FOREIGN KEY(answer_id,statement_ordinal) REFERENCES answer_statements(answer_id,ordinal) ON DELETE CASCADE, FOREIGN KEY(answer_id,source_ordinal) REFERENCES answer_sources(answer_id,ordinal));
CREATE INDEX meetings_date ON meetings(meeting_date); CREATE INDEX meetings_status ON meetings(status); CREATE INDEX participants_name ON meeting_participants(name,meeting_id);
CREATE INDEX revisions_meeting ON memory_revisions(meeting_id); CREATE INDEX sources_order ON source_units(revision_id,kind,ordinal);
CREATE INDEX speaker_names ON speakers(confirmed_name,evidence_id); CREATE INDEX segments_speaker ON transcript_segments(evidence_id,speaker_id,start_offset);
CREATE INDEX generations_meeting ON memory_generations(meeting_id,status); CREATE INDEX chunks_generation ON memory_source_chunks(generation_id); CREATE INDEX chunk_source_lookup ON chunk_sources(unit_key);
CREATE INDEX jobs_status_lease ON memory_jobs(status,lease_until); CREATE INDEX answers_created ON answers(created_at); CREATE INDEX answer_sources_meeting ON answer_sources(meeting_id); CREATE INDEX answer_citations_source ON answer_citations(answer_id,source_ordinal);
CREATE TRIGGER published_meeting_guard BEFORE UPDATE OF published_generation_id ON meetings WHEN NEW.published_generation_id IS NOT NULL BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM memory_generations g WHERE g.id=NEW.published_generation_id AND g.meeting_id=NEW.id AND g.status='published' AND g.internal_building=0) THEN RAISE(ABORT,'Current generation must be completely published for this meeting') END;
END;
CREATE TRIGGER revision_original_immutable BEFORE UPDATE OF original_text,content_hash,evidence_id ON memory_revisions WHEN NEW.original_text IS NOT OLD.original_text OR NEW.content_hash IS NOT OLD.content_hash OR NEW.evidence_id IS NOT OLD.evidence_id BEGIN SELECT RAISE(ABORT,'Transcript revisions are immutable'); END;
CREATE TRIGGER source_unit_immutable BEFORE UPDATE ON source_units BEGIN SELECT RAISE(ABORT,'Source units are immutable'); END;
CREATE TRIGGER speaker_version_immutable BEFORE UPDATE ON speakers BEGIN SELECT RAISE(ABORT,'Speaker names require a new evidence version'); END;
CREATE TRIGGER segment_immutable BEFORE UPDATE ON transcript_segments BEGIN SELECT RAISE(ABORT,'Source segments are immutable'); END;
CREATE TRIGGER published_generation_immutable BEFORE UPDATE ON memory_generations WHEN OLD.internal_building=0 BEGIN SELECT RAISE(ABORT,'Published generations are immutable'); END;
CREATE TRIGGER chunk_immutable BEFORE UPDATE ON memory_source_chunks BEGIN SELECT RAISE(ABORT,'Published chunks are immutable'); END;
CREATE TRIGGER original_revision_owner BEFORE UPDATE OF original_revision_id ON meetings WHEN OLD.original_revision_id IS NOT NEW.original_revision_id AND NOT EXISTS(SELECT 1 FROM memory_revisions r WHERE r.id=NEW.original_revision_id AND r.meeting_id=NEW.id) BEGIN SELECT RAISE(ABORT,'Original revision must belong to this meeting'); END;
`;
